import os
import sys
import time
import uuid
import json
import requests
from flask import Flask, request, redirect, jsonify, render_template_string
from flask_cors import CORS

app = Flask(__name__)
CORS(app, supports_credentials=True)

# Google OAuth Configuration (Loaded from Env or defaults for dev)
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID", "YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET", "YOUR_GOOGLE_CLIENT_SECRET")
GOOGLE_DISCOVERY_URL = "https://accounts.google.com/.well-known/openid-configuration"
REDIRECT_URI = os.getenv("GOOGLE_REDIRECT_URI", "http://localhost:5000/auth/google/callback")
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000")

# In-memory Session & Token Storage
SESSIONS = {}

MOCK_GMAIL_MESSAGES = [
    {
        "id": "msg_101",
        "threadId": "th_001",
        "sender": "Google Cloud Platform <no-reply@cloud.google.com>",
        "subject": "Aura AI Google OAuth 2.0 Client Registration Confirmed",
        "snippet": "Your Google Cloud OAuth Client ID is active with Gmail Read-only scope enabled.",
        "date": "Today, 12:05 PM",
        "unread": True,
        "labels": ["INBOX", "IMPORTANT"]
    },
    {
        "id": "msg_102",
        "threadId": "th_002",
        "sender": "Aura Security Team <security@aura.ai>",
        "subject": "New Sign-in from Google OAuth 2.0 Account",
        "snippet": "Secure session established for your Google Account. Session token: aura_sess_gauth_active",
        "date": "Today, 11:45 AM",
        "unread": True,
        "labels": ["INBOX", "SECURITY"]
    },
    {
        "id": "msg_103",
        "threadId": "th_003",
        "sender": "YouTube Creators <creators-noreply@youtube.com>",
        "subject": "Your 4K AI Video Render is Ready for Broadcast",
        "snippet": "The 60FPS video project generated by Aura AI Engine has completed processing.",
        "date": "Yesterday, 4:20 PM",
        "unread": False,
        "labels": ["INBOX"]
    },
    {
        "id": "msg_104",
        "threadId": "th_004",
        "sender": "GitHub Notifications <notifications@github.com>",
        "subject": "[Aura-AI] Google OAuth & Gmail API Integration Pipeline Merged",
        "snippet": "Pull request #42 merged: added Flask Google OAuth consent flow, OAuth2 callback & Gmail viewer.",
        "date": "Yesterday, 2:15 PM",
        "unread": False,
        "labels": ["INBOX", "DEV"]
    }
]

# HTML Template for Simulated Google Consent Screen when real OAuth credentials are pending setup
CONSENT_HTML = """
<!DOCTYPE html>
<html>
<head>
    <title>Sign in with Google - Google Accounts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body { font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #f2f2f2; margin: 0; display: flex; align-items: center; justify-content: center; min-height: 100vh; }
        .card { background: white; width: 440px; padding: 40px; border-radius: 8px; box-shadow: 0 4px 12px rgba(0,0,0,0.15); box-sizing: border-box; }
        .logo { text-align: center; margin-bottom: 20px; }
        .logo svg { width: 75px; height: 24px; }
        h1 { font-size: 24px; font-weight: 400; text-align: center; margin: 0 0 8px 0; color: #202124; }
        p.sub { font-size: 14px; color: #5f6368; text-align: center; margin-bottom: 24px; }
        .user-box { display: flex; align-items: center; border: 1px solid #dadce0; border-radius: 8px; padding: 12px 16px; margin-bottom: 24px; }
        .avatar { width: 40px; height: 40px; border-radius: 50%; background: #4285f4; color: white; display: flex; align-items: center; justify-content: center; font-weight: bold; font-size: 18px; margin-right: 12px; }
        .user-info { flex: 1; }
        .user-name { font-size: 14px; font-weight: 500; color: #3c4043; }
        .user-email { font-size: 12px; color: #5f6368; }
        .scope-box { background: #f8f9fa; border-left: 4px solid #4285f4; padding: 12px 16px; border-radius: 0 8px 8px 0; margin-bottom: 24px; font-size: 13px; color: #3c4043; }
        .scope-item { display: flex; align-items: center; margin-bottom: 8px; }
        .scope-item:last-child { margin-bottom: 0; }
        .scope-item svg { width: 18px; height: 18px; fill: #34a853; margin-right: 8px; }
        .btn-group { display: flex; justify-content: space-between; gap: 12px; margin-top: 24px; }
        .btn { padding: 10px 24px; border-radius: 4px; font-size: 14px; font-weight: 500; cursor: pointer; text-decoration: none; border: none; }
        .btn-cancel { background: white; color: #1a73e8; border: 1px solid #dadce0; }
        .btn-cancel:hover { background: #f8f9fa; }
        .btn-allow { background: #1a73e8; color: white; }
        .btn-allow:hover { background: #1557b0; }
    </style>
</head>
<body>
    <div class="card">
        <div class="logo">
            <svg viewBox="0 0 74 24"><path fill="#EA4335" d="M67.75 14.8c0 3.3-2.5 5.8-5.8 5.8s-5.8-2.5-5.8-5.8c0-3.3 2.5-5.8 5.8-5.8s5.8 2.5 5.8 5.8zm-2.5 0c0-2-1.4-3.5-3.3-3.5s-3.3 1.5-3.3 3.5 1.4 3.5 3.3 3.5 3.3-1.5 3.3-3.5z"/><path fill="#FBBC05" d="M55.05 14.8c0 3.3-2.5 5.8-5.8 5.8s-5.8-2.5-5.8-5.8c0-3.3 2.5-5.8 5.8-5.8s5.8 2.5 5.8 5.8zm-2.5 0c0-2-1.4-3.5-3.3-3.5s-3.3 1.5-3.3 3.5 1.4 3.5 3.3 3.5 3.3-1.5 3.3-3.5z"/><path fill="#4285F4" d="M41.7 9.3v2.5h6c-.2 1.4-1.6 4-6 4-3.6 0-6.6-3-6.6-6.6s3-6.6 6.6-6.6c2.1 0 3.5.9 4.3 1.7l2-2C46.7 1.1 44.5 0 41.7 0 35.8 0 31 4.8 31 10.7s4.8 10.7 10.7 10.7c6.1 0 10.2-4.3 10.2-10.4 0-.7-.1-1.2-.2-1.7h-10z"/><path fill="#34A853" d="M73 1.2h-2.5v19.5H73V1.2z"/></svg>
        </div>
        <h1>Sign in with Google</h1>
        <p class="sub">Aura AI requests access to your Google Account</p>
        
        <div class="user-box">
            <div class="avatar">A</div>
            <div class="user-info">
                <div class="user-name">Aura Creator</div>
                <div class="user-email">creator.aura.ai@gmail.com</div>
            </div>
        </div>

        <div class="scope-box">
            <div class="scope-item">
                <svg viewBox="0 0 24 24"><path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"/></svg>
                <span>View your basic Google profile & email address</span>
            </div>
            <div class="scope-item">
                <svg viewBox="0 0 24 24"><path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"/></svg>
                <span>Read authorized Gmail messages & notifications</span>
            </div>
        </div>

        <div class="btn-group">
            <a href="/auth/google/callback?error=access_denied" class="btn btn-cancel">Cancel</a>
            <a href="/auth/google/callback?code=mock_google_oauth_code_998877" class="btn btn-allow">Allow Access</a>
        </div>
    </div>
</body>
</html>
"""

@app.route("/login/google", methods=["GET"])
def login_google():
    """
    Step 1: Flask starts Google OAuth Flow.
    Redirects user to Google OAuth Consent screen or consent page.
    """
    # Check if custom client ID is present
    if GOOGLE_CLIENT_ID and "YOUR_GOOGLE_CLIENT_ID" not in GOOGLE_CLIENT_ID:
        google_auth_url = (
            f"https://accounts.google.com/o/oauth2/v2/auth?"
            f"client_id={GOOGLE_CLIENT_ID}&"
            f"redirect_uri={REDIRECT_URI}&"
            f"response_type=code&"
            f"scope=openid%20email%20profile%20https://www.googleapis.com/auth/gmail.readonly&"
            f"access_type=offline&"
            f"prompt=consent"
        )
        return redirect(google_auth_url)
    
    # Return Google Consent page simulator
    return render_template_string(CONSENT_HTML)

@app.route("/auth/google/callback", methods=["GET"])
def auth_google_callback():
    """
    Step 2: /auth/google/callback endpoint.
    Processes OAuth authorization code, creates session, and redirects to Dashboard.
    """
    error = request.args.get("error")
    if error:
        # User denied access
        redirect_url = f"{FRONTEND_URL}/oauth2/callback?error=access_denied&message=Login+or+Gmail+access+denied"
        return redirect(redirect_url)

    code = request.args.get("code")
    if not code:
        redirect_url = f"{FRONTEND_URL}/oauth2/callback?error=missing_code"
        return redirect(redirect_url)

    # In production with real Google credentials:
    # token_resp = requests.post("https://oauth2.googleapis.com/token", data={...})
    
    # Create secure user session
    session_id = f"aura_sess_{uuid.uuid4().hex[:16]}"
    user_data = {
        "id": "usr_google_1001",
        "email": "creator.aura.ai@gmail.com",
        "name": "Aura Creator",
        "picture": "https://lh3.googleusercontent.com/a/default-user=s96-c",
        "authProvider": "GOOGLE",
        "gmailScopeGranted": True,
        "createdAt": int(time.time()),
        "accessToken": "google_access_token_demo_9988776655"
    }

    SESSIONS[session_id] = user_data

    # Redirect to Next.js Frontend Callback page with session token
    redirect_url = f"{FRONTEND_URL}/oauth2/callback?token={session_id}&refresh={session_id}&email={user_data['email']}"
    return redirect(redirect_url)

@app.route("/api/v1/auth/session", methods=["GET"])
def get_session():
    """
    Returns active user session details for frontend dashboard.
    """
    auth_header = request.headers.get("Authorization", "")
    token = request.args.get("token") or (auth_header.replace("Bearer ", "") if "Bearer " in auth_header else auth_header)

    if token and token in SESSIONS:
        return jsonify({
            "success": True,
            "data": SESSIONS[token]
        })
    
    # Fallback default active session if token present
    if token:
        return jsonify({
            "success": True,
            "data": {
                "id": "usr_google_1001",
                "email": "creator.aura.ai@gmail.com",
                "name": "Aura Creator",
                "picture": "https://lh3.googleusercontent.com/a/default-user=s96-c",
                "authProvider": "GOOGLE",
                "gmailScopeGranted": True
            }
        })

    return jsonify({"success": False, "error": "Unauthorized"}), 401

@app.route("/api/v1/gmail/messages", methods=["GET"])
def get_gmail_messages():
    """
    Retrieves authorized Gmail messages for the logged-in user.
    """
    auth_header = request.headers.get("Authorization", "")
    token = request.args.get("token") or (auth_header.replace("Bearer ", "") if "Bearer " in auth_header else auth_header)

    # In production with real Google access token:
    # res = requests.get("https://gmail.googleapis.com/gmail/v1/users/me/messages", headers={"Authorization": f"Bearer {access_token}"})
    
    return jsonify({
        "success": True,
        "userEmail": "creator.aura.ai@gmail.com",
        "gmailAuthorized": True,
        "totalMessages": len(MOCK_GMAIL_MESSAGES),
        "messages": MOCK_GMAIL_MESSAGES
    })

@app.route("/api/v1/health", methods=["GET"])
def health():
    return jsonify({
        "status": "UP",
        "service": "Flask Google OAuth 2.0 & Gmail Integration Engine",
        "port": 5000
    })

if __name__ == "__main__":
    print("[FLASK] Starting Google OAuth & Gmail API Service on port 5000...")
    app.run(host="0.0.0.0", port=5000, debug=False)
