package com.aura.user.entity;

public enum PermissionName {
    VIDEO_VIEW,
    VIDEO_GENERATE,
    VIDEO_DELETE,
    VIDEO_DOWNLOAD,
    TEMPLATE_USE,
    TEMPLATE_CREATE,
    TEMPLATE_DELETE,
    WORKSPACE_MANAGE,
    TEAM_MANAGE,
    BILLING_VIEW,
    BILLING_MANAGE,
    ADMIN_ACCESS,
    ADMIN_USERS,
    ADMIN_ANALYTICS,
    ADMIN_PROVIDERS,
    API_KEY_CREATE,
    API_KEY_DELETE
}
