input {
  beats {
    port => 5044
  }
}

filter {
  if [message] =~ /^\{.*/ {
    json {
      source => "message"
      target => "parsed_json"
    }
    
    mutate {
      add_field => { "environment" => "%{[@metadata][env]}" }
      add_field => { "service" => "%{[@metadata][service]}" }
    }
  } else {
    grok {
      match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} \[%{THREADNAME:thread}\] %{LOGLEVEL:level} %{JAVACLASS:class} - %{GREEDYDATA:log_message}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "aura-logs-%{+YYYY.MM.dd}"
    # user => "elastic"
    # password => "changeme"
  }
  stdout { codec => rubydebug }
}
